import type { Metadata } from "next";
import Link from "next/link";
import Converter from "../../../converter";
import { getCurrency } from "@/lib/currencies";
import { getGuide } from "@/lib/guides";
import AdBanner from "@/components/ads/AdBanner";

type Props = { params: Promise<{ from: string; to: string }> };
const relatedGuideSlugs = ["what-is-an-exchange-rate", "how-currency-conversion-works", "bank-rates-vs-mid-market"];
export async function generateMetadata({ params }: Props): Promise<Metadata> { const { from, to } = await params; const source = getCurrency(from.toUpperCase()); const target = getCurrency(to.toUpperCase()); const fromCode = from.toLowerCase(); const toCode = to.toLowerCase(); return { title: `${from.toUpperCase()} to ${to.toUpperCase()} Converter | GlobalConvert`, description: `Convert ${source?.name || from} to ${target?.name || to} with current provider reference data and practical conversion guidance.`, alternates: { canonical: `/convert/${fromCode}/${toCode}` }, openGraph: { title: `${from.toUpperCase()} to ${to.toUpperCase()} Converter | GlobalConvert`, description: `Convert ${source?.name || from} to ${target?.name || to} with GlobalConvert.` } }; }
export default async function PairPage({ params }: Props) { const { from: rawFrom, to: rawTo } = await params; const from = rawFrom.toUpperCase(); const to = rawTo.toUpperCase(); const source = getCurrency(from); const target = getCurrency(to); if (!/^[A-Z]{3}$/.test(from) || !/^[A-Z]{3}$/.test(to)) return null; return <><header className="site-header"><Link className="brand" href="/"><span className="brand-mark">↗</span> Global<span>Convert</span></Link><Link href="/#converter">← Back to converter</Link></header><main className="pair-page"><div><p className="eyebrow">PAIR CONVERTER</p><h1>{from} <span>→</span> {to}</h1><p>Convert {source?.name || from} to {target?.name || to} using provider reference data. The first currency is the base and the second is the quote currency.</p><section className="pair-copy"><h2>How to read {from}/{to}</h2><p>A rate of 1 {from} = 10 {to}, for example, means one unit of {source?.name || from} corresponds to ten units of {target?.name || to} at that reference rate. Actual values change as provider data updates.</p><h2>Before using the result</h2><p>Banks, card providers, exchange bureaus, and money-transfer services may apply different rates, spreads, and fees. Confirm the final amount with the provider completing your transaction.</p><h2>Related guides</h2><ul>{relatedGuideSlugs.map((slug) => { const guide = getGuide(slug); return guide ? <li key={slug}><Link href={`/guides/${slug}`}>{guide.title}</Link></li> : null; })}</ul><p><Link href="/rate-methodology">Read the full rate methodology</Link>.</p></section><AdBanner slot="pair-sidebar" /></div><div><Converter /><AdBanner slot="pair-after-converter" className="ad-secondary" /></div></main></>; }
