const operator = process.env.OPERATOR_NAME || "Global Currency Converter";
const email = "globalcurrencyconverter01020@gmail.com";

export default function PrivacyContent() {
  return <main className="legal"><a className="brand" href="/">↗ Global<span>Convert</span></a><article>
    <p className="eyebrow">PRIVACY POLICY</p><h1>Privacy Policy</h1><p>Effective date: September 5, 2026</p><p>Welcome to Global Currency Converter. This policy explains how {operator} may collect, use, store, and share information when you use our website.</p>
    <h2>Information we may collect</h2><p>You may provide your name, email address, and message when contacting us. Our systems, hosting providers, security providers, analytics providers, and advertising partners may automatically process IP address, browser and device type, operating system, language, approximate location, pages visited, referring page, visit time, interactions, cookies, and similar identifiers.</p>
    <h2>How we use information</h2><p>We may use information to operate conversion tools, provide exchange-rate results, improve performance, respond to enquiries, detect abuse and security incidents, measure advertising, and comply with law.</p>
    <h2>Currency conversion data</h2><p>Currencies and amounts selected in the public converter may be processed to provide the requested result. An account is not required for ordinary conversions. Requests may be logged temporarily for security, troubleshooting, throttling, and reliability.</p>
    <h2>Cookies and similar technologies</h2><p>We and our providers may use cookies, local storage, web beacons, pixels, tags, or similar technologies for preferences, functionality, security, analytics, and future advertising. See our <a href="/cookies">Cookie Policy</a>.</p>
    <h2>Advertising and Google services</h2><p>GlobalConvert may display advertising in the future, including advertising provided by third-party partners such as Google. If enabled, those partners may use cookies, web beacons, IP addresses, or identifiers to serve, measure, personalize, limit, and improve advertisements, subject to applicable law and consent requirements. AdSense is not active while advertising is disabled in the deployment configuration.</p><p>For more information, see <a href="https://policies.google.com/technologies/partner-sites" rel="noreferrer">How Google uses information from sites or apps that use Google services</a>.</p>
    <h2>Third-party providers and sharing</h2><p>We may use hosting, security, exchange-rate data, analytics, consent, monitoring, and advertising providers. We may share information with those providers, professional advisers, authorities where legally required, or a successor organisation. We do not sell personal information in a manner inconsistent with applicable privacy laws.</p>
    <h2>Retention, security, and international transfers</h2><p>We retain information only as reasonably necessary for the purposes described here or as required by law. We use reasonable administrative, technical, and organisational safeguards, but no internet transmission or storage method is completely secure. Providers may process information in countries other than your own.</p>
    <h2>Your choices and rights</h2><p>Depending on your location and applicable law, you may request access, correction, deletion, restriction, objection, or information about our practices, and withdraw consent where processing is based on consent. Contact <a href={`mailto:${email}`}>{email}</a>; we may verify your identity.</p>
    <h2>Children, external links, and changes</h2><p>We do not knowingly collect children’s personal information in violation of applicable law. External websites have their own policies. We may update this policy and will revise the effective date when appropriate.</p>
    <h2>Contact</h2><p>Privacy questions can be sent to <a href={`mailto:${email}`}>{email}</a>.</p>
  </article></main>;
}
